export const PERMITS = [
  // Core / Almost Always Required
  {
    id: "1",
    name: "Wastewater System & Potable Water Supply",
    agency: "DEC Wastewater Management Division",
    category: "core",
    sla_days: 30,
    why: "Required for any new construction with water/sewer",
    trigger: () => true,
    sheet: "#1",
    description: "Ensures proper design and installation of wastewater and potable water systems to protect public health and water quality.",
    url: "https://dec.vermont.gov/water-investment/wastewater",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet01.pdf",
  },
  {
    id: "2",
    name: "Land Subdivision",
    agency: "DEC Wastewater Management Division",
    category: "core",
    sla_days: 45,
    why: "Required if creating separate lots",
    trigger: (c) => c.creating_lots,
    sheet: "#2",
    description: "Required when dividing land into two or more parcels.",
    url: "https://dec.vermont.gov/water-investment/wastewater/subdivision",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet02.pdf",
  },
  {
    id: "5",
    name: "Extension of Sewer Lines",
    agency: "DEC Wastewater Management Division",
    category: "core",
    sla_days: 30,
    why: "If connecting to municipal sewer",
    trigger: (c) => c.connects_municipal_sewer,
    sheet: "#5",
    description: "Required for any extension of public sewer lines to serve new development.",
    url: "https://dec.vermont.gov/water-investment/wastewater",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet05.pdf",
  },
  {
    id: "6.1",
    name: "Stormwater – Construction Sites",
    agency: "DEC Watershed Management Division",
    category: "core",
    sla_days: 30,
    why: "Triggered if disturbing ≥1 acre",
    trigger: (c) => c.disturbed_acres >= 1,
    sheet: "#6.1",
    description: "Required for construction sites disturbing one or more acres of land.",
    url: "https://dec.vermont.gov/watershed-management/stormwater",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet06_1.pdf",
  },
  {
    id: "6.2",
    name: "Stormwater – New Development",
    agency: "DEC Watershed Management Division",
    category: "core",
    sla_days: 30,
    why: "Triggered if ≥1 acre impervious surface",
    trigger: (c) => c.disturbed_acres >= 1,
    sheet: "#6.2",
    description: "Required for new development with one or more acres of impervious surface.",
    url: "https://dec.vermont.gov/watershed-management/stormwater",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet06_2.pdf",
  },
  {
    id: "49",
    name: "Fire Safety Construction Permit",
    agency: "Division of Fire Safety",
    category: "core",
    sla_days: 20,
    why: "Required for multi-unit public buildings",
    trigger: (c) => c.unit_count >= 4,
    sheet: "#49",
    description: "Required for all multi-family buildings to ensure compliance with fire and life safety codes.",
    url: "https://firesafety.vermont.gov",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet49.pdf",
  },
  {
    id: "50",
    name: "Electrical Permit",
    agency: "Division of Fire Safety",
    category: "core",
    sla_days: 10,
    why: "Required for all electrical in public buildings",
    trigger: () => true,
    sheet: "#50",
    description: "Required for all electrical work in multi-family residential buildings.",
    url: "https://firesafety.vermont.gov/buildings/electrical",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet50.pdf",
  },
  {
    id: "50.1",
    name: "Energizing Permit",
    agency: "Division of Fire Safety / Utility",
    category: "core",
    sla_days: 10,
    why: "Required before utility energizes service",
    trigger: () => true,
    sheet: "#50.1",
    description: "Required before electric utility can energize new service to a building.",
    url: "https://firesafety.vermont.gov/buildings/electrical",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet50_1.pdf",
  },
  {
    id: "50.2",
    name: "Plumbing Permit",
    agency: "Division of Fire Safety",
    category: "core",
    sla_days: 10,
    why: "Required if connected to public water/sewer",
    trigger: (c) => c.connects_municipal_sewer,
    sheet: "#50.2",
    description: "Required for all plumbing work in buildings connected to public water or sewer.",
    url: "https://firesafety.vermont.gov/buildings/plumbing",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet50_2.pdf",
  },
  {
    id: "47.2",
    name: "Residential Building Energy Standards (RBES)",
    agency: "Dept. of Public Service",
    category: "core",
    sla_days: 20,
    why: "Applies to all multi-family ≤3 stories",
    trigger: (c) => c.unit_count <= 9,
    sheet: "#47.2",
    description: "Vermont's energy efficiency standards for residential buildings of 3 stories or less.",
    url: "https://publicservice.vermont.gov/content/rbes",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet47_2.pdf",
  },

  // Likely Required
  {
    id: "29",
    name: "Wetlands Permit",
    agency: "DEC Watershed Management Division",
    category: "likely",
    sla_days: 60,
    why: "If site has or is near Class I/II wetlands",
    trigger: (c) => c.near_wetlands,
    sheet: "#29",
    description: "Required for any work in or near Class I or Class II wetlands.",
    url: "https://dec.vermont.gov/watershed-management/wetlands",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet29.pdf",
  },
  {
    id: "32.3",
    name: "Flood Hazard Area Permit",
    agency: "DEC Watershed Management Division",
    category: "likely",
    sla_days: 45,
    why: "If site is in or near FEMA 100-year floodplain",
    trigger: (c) => c.in_floodplain,
    sheet: "#32.3",
    description: "Required for development in designated flood hazard areas.",
    url: "https://dec.vermont.gov/watershed-management/rivers/flood-hazard-area",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet32_3.pdf",
  },
  {
    id: "32",
    name: "Stream Alterations",
    agency: "DEC Watershed Management Division",
    category: "likely",
    sla_days: 45,
    why: "If any stream crossing or work near perennial stream",
    trigger: (c) => c.near_stream,
    sheet: "#32",
    description: "Required for any alteration to or work near a perennial stream.",
    url: "https://dec.vermont.gov/watershed-management/rivers",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet32.pdf",
  },
  {
    id: "66",
    name: "Work in State Highway Right-of-Way",
    agency: "VTrans",
    category: "likely",
    sla_days: 30,
    why: "If driveway access is off a state highway",
    trigger: (c) => c.state_highway_access,
    sheet: "#66",
    description: "Required if the project requires access from or work within a state highway right-of-way.",
    url: "https://vtrans.vermont.gov",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet66.pdf",
  },
  {
    id: "54",
    name: "Asbestos Control",
    agency: "DEC Air Quality & Climate Division",
    category: "likely",
    sla_days: 20,
    why: "If demolishing or renovating any existing building on site",
    trigger: (c) => c.existing_structures,
    sheet: "#54",
    description: "Required before demolishing or extensively renovating any existing structure.",
    url: "https://dec.vermont.gov/air-quality/asbestos",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet54.pdf",
  },
  {
    id: "55.1",
    name: "Lead-Based Paint (RRPM)",
    agency: "Health Dept.",
    category: "likely",
    sla_days: 15,
    why: "If renovating pre-1978 structures on site",
    trigger: (c) => c.pre_1978_structures,
    sheet: "#55.1",
    description: "Required for renovation, repair, or painting in pre-1978 structures.",
    url: "https://www.healthvermont.gov/environment/environmental-health/lead",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet55_1.pdf",
  },

  // Conditional
  {
    id: "47",
    name: "Act 250 Land Use Permit",
    agency: "Natural Resources Board",
    category: "conditional",
    sla_days: 180,
    why: "Triggered at 10+ units; may also be triggered by acreage or elevation",
    trigger: (c) => c.unit_count >= 10 || c.elevation_above_2500,
    sheet: "#47",
    description: "Vermont's major land use permit. Required for 10+ unit projects and certain other thresholds.",
    url: "https://nrb.vermont.gov/act250",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet47.pdf",
  },
  {
    id: "21",
    name: "Public Water System – Operating Permit",
    agency: "DEC Drinking Water & Groundwater Protection",
    category: "conditional",
    sla_days: 60,
    why: "If project creates own water system serving 15+ connections or 25+ people",
    trigger: (c) => c.own_water_system,
    sheet: "#21",
    description: "Required for any public water system serving 15 or more connections or 25 or more people.",
    url: "https://dec.vermont.gov/drinking-water",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet21.pdf",
  },
  {
    id: "22",
    name: "Public Water System – Construction Permit",
    agency: "DEC Drinking Water & Groundwater Protection",
    category: "conditional",
    sla_days: 45,
    why: "Same trigger as Operating Permit",
    trigger: (c) => c.own_water_system,
    sheet: "#22",
    description: "Required before constructing a public water system.",
    url: "https://dec.vermont.gov/drinking-water",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet22.pdf",
  },
  {
    id: "28.1",
    name: "Shoreland Protection Permit",
    agency: "DEC Watershed Management Division",
    category: "conditional",
    sla_days: 45,
    why: "If within 250 ft of a lake or pond >10 acres",
    trigger: (c) => c.near_lake_or_pond,
    sheet: "#28.1",
    description: "Required for development within 250 feet of a lake or pond larger than 10 acres.",
    url: "https://dec.vermont.gov/watershed-management/lakes-ponds/shoreland-protection",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet28_1.pdf",
  },
  {
    id: "28",
    name: "Lake Encroachment Permit",
    agency: "DEC Watershed Management Division",
    category: "conditional",
    sla_days: 60,
    why: "If any work in or encroaching on a public water body",
    trigger: (c) => c.near_lake_or_pond,
    sheet: "#28",
    description: "Required for any physical encroachment on or into a public water body.",
    url: "https://dec.vermont.gov/watershed-management/lakes-ponds",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet28.pdf",
  },
  {
    id: "101",
    name: "Federal Section 106 Historic Properties",
    agency: "VT Division for Historic Preservation",
    category: "conditional",
    sla_days: 90,
    why: "If federal funding or permits (e.g., Army Corps) involved",
    trigger: (c) => c.federal_funding,
    sheet: "#101",
    description: "Required when federal funding or federal permits are involved in the project.",
    url: "https://accd.vermont.gov/historic-preservation",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet101.pdf",
  },
  {
    id: "97",
    name: "Federal Wetlands (Army Corps 404)",
    agency: "US Army Corps of Engineers",
    category: "conditional",
    sla_days: 120,
    why: "If filling wetlands or waters of the US",
    trigger: (c) => c.near_wetlands && c.federal_funding,
    sheet: "#97",
    description: "Federal permit required for any filling of wetlands or waters of the United States.",
    url: "https://www.nae.usace.army.mil/Missions/Regulatory/",
    info_sheet_url: "https://dec.vermont.gov/sites/dec/files/permit-handbook/sheet97.pdf",
  },
];

export const STATUS_CONFIG = {
  not_started: { label: "Not Started", color: "#718096", bg: "#edf2f7" },
  in_progress: { label: "In Progress", color: "#2980b9", bg: "#ebf5fb" },
  submitted: { label: "Submitted", color: "#6d28d9", bg: "#ede9fe" },
  under_review: { label: "Under Review", color: "#b7791f", bg: "#fffbeb" },
  info_requested: { label: "Info Requested", color: "#c05621", bg: "#fff5e6" },
  approved: { label: "Approved", color: "#15803d", bg: "#dcfce7" },
  denied: { label: "Denied", color: "#b91c1c", bg: "#fee2e2" },
};

export const CATEGORY_CONFIG = {
  core: { label: "Core", className: "vt-badge-core" },
  likely: { label: "Likely Required", className: "vt-badge-likely" },
  conditional: { label: "Conditional", className: "vt-badge-conditional" },
};

export function determinePermits(conditions) {
  return PERMITS.filter(p => p.trigger(conditions));
}